#!/usr/bin/env python

import urllib
import hashlib
import subprocess
import urllib
import urlparse
import os
import xml.dom.minidom
import argparse
import time
import tempfile
import shutil
import plistlib

# Constants.
PICTURE_FILE = "~/.gravatar.jpg"
SIZE = 200

# Derived properties.
picture = os.path.expanduser(PICTURE_FILE) 

def dscl(command, arguments):
  user = os.path.expanduser("~")
  result = subprocess.check_output(["dscl", ".", command, user] + arguments,
                                   stderr=subprocess.STDOUT)
  return result

def dscl_read(key):
  user = os.path.expanduser("~")
  result = subprocess.check_output(["dscl", "-plist", ".", "-read", user, key],
                                   stderr=subprocess.STDOUT)
  data = plistlib.readPlistFromString(result)
  if (data):
    return data.itervalues().next()[0]
  return None

def dscl_delete(key):
  return dscl("-delete", [key])

def dscl_create(key, value):
  return dscl("-create", [key, value])

def dscl_update(key, value):
  old_value = dscl_read(key)
  if (old_value):
    dscl("-change", [key, old_value, value])
  else:
    dscl("-create", [key, value])

def set_profile_picture(path):
  try:
    dscl_update("Picture", path)
    dscl_delete("JPEGPhoto")
  except:
    print "Unable to set the profile picture. Did you run with administrative privileges?"
    exit(1)

def update(email):

  # Construct the url.
  gravatar = "http://www.gravatar.com/avatar/" + hashlib.md5(email.lower()).hexdigest() + "?"
  gravatar += urllib.urlencode({'s':str(SIZE)})

  # Create a temporary location to download the file.
  temp_dir = tempfile.mkdtemp()
  temp_file = os.path.join(temp_dir, "gravatar.jpg")

  try:

    # Download the profile picture.
    print "Downloading Gravatar..."
    urllib.urlretrieve(gravatar, temp_file)

    # Copy the picture to the final destination (once we know we have
    # successfully retieved it).
    if (os.path.exists(picture)):
      os.unlink(picture)
    shutil.move(temp_file, picture)
    path = os.path.abspath(picture)

    # Set the picture.
    print "Setting profile picture..."
    set_profile_picture(path)

    # Log the success.
    print "Success."

  finally:
    
    # Clean up the temporary location.
    shutil.rmtree(temp_dir)

def main():
  
  parser = argparse.ArgumentParser(description = "Set your account picture to your Gravatar.")
  parser.add_argument('email', help = 'Email account for which to fetch the avatar')
  options = parser.parse_args()

  update(options.email)


if __name__ == '__main__':
  main()

